#!/bin/sh

# Exit on error
set -e

# download and check a file
download_file() {
	FILE=`basename $1`

	if [ ! -f $FILE ]; then
		curl -L $1 > $FILE
	else
		echo "$FILE already exists"
	fi

	if [ x"$2" != x`sha256sum $FILE | cut -d ' ' -f 1` ]; then
		echo "SHA256 mismatch for $FILE" >&2
		exit 1
	fi
}

# check if clean is requested
for arg in "$@"; do
	case "$arg" in
		-c|--clean) do_clean=yes ;;
	esac
done

# check if curl is installed
if [ ! -x `command -v curl` ]; then
	echo "Please install curl" >&2
	exit 1
fi

parse_src() {
	source $1
	FILE=`basename $URL`
	if [ ! -f $FILE ]; then
	 	curl -L $URL > $FILE
	fi
	NAME=`basename $1`-$VER
	if [ ! -d $NAME ]; then
		tar xf $FILE
		cd $NAME
		for p in "${PATCHES[@]}"; do
			eval "$p"
		done
		cd ..
	fi
}

for s in `ls list`; do
	if [ x$do_clean = xyes ]; then
		rm -rf $s*
	else
		parse_src list/$s
	fi
done
